[build]
  command = "cd site && yarn build"
  publish = "./site/public"

[build.environment]
  NETLIFY_USE_YARN = "true"

[context.production]
  [context.production.environment]
    CONTENTFUL_SPACE_ID="y7mzv4t1cbj8"
    CONTENTFUL_ACCESS_TOKEN="dO7HmtJuS4djRxC6UVWjABD88dLCHFGowm2_n-ly2Mk"
    GATSBY_ALGOLIA_APP_ID=""
    GATSBY_ALGOLIA_SEARCH_KEY=""
    ALGOLIA_ADMIN_KEY=""
    GATSBY_ALGOLIA_INDEX_NAME="Posts"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/authors"
  to = "/404"
  status = 301
  force = true